## Luis Elias Barral Larios
print("\nEjercicio 7")
print("Realiza un programa que lea 2 números por teclado y determine los siguientes aspectos: ")
print("- Si los dos números son iguales")
print("- Si los dos números son diferentes")
print("-Si el primero es mayor que el segundo")
print("- Si el segundo es mayor o igual que el primero")
n1=input('\nIngrese el primer valor: ')
n2=input('Ingrese el segundo valor: ')

print("\n")
print(n1==n2)
print(n1!=n2)
print(n1>n2)
print(n2>=n1)